branches:
  only:
    - master
cache:
  directories:
    - $HOME/.npm
    - examples/composition/node_modules
    - examples/simple/node_modules
language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "node"
script:
  - npm run eslint
  - npm run flow
  - npm run build
  - npm run test
  - cd examples/composition && npm i && npm run flow && npm run build && npm run test && cd ../..
  - cd examples/simple && npm i && npm run flow && npm run build && npm run test && cd ../..
